/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ui5vq4jd55dtfeezlqcoiyeeue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pnh7w4q5azeajaqje72sidg35i",
    "aws_cognito_identity_pool_id": "us-east-1:6fb67c3c-aeeb-4cac-9e2f-b36414933c50",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_54V5WeNBj",
    "aws_user_pools_web_client_id": "63ltd9mgi57il6jsc2ab47rtfi",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "portfolio-storage-5d6b1c7f02221-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
